### ISSUE TITLE
Download of datasets fails because of wrong parameter names

### ISSUE THREAD

**Issue by AbeleMM** [JMGaljaard/fltk-testbed#22]
## Bug Report

**Current Behavior**
Running `python3 -m fltk extractor ./configs/example_cloud_experiment.json` from the project root, after having successfully installed `requirements-cpu.txt`, fails with the following message:
```
/fltk-testbed/venv/lib/python3.8/site-packages/dataclasses_json/core.py:171: RuntimeWarning: `NoneType` object value of non-optional type config_path detected when decoding DistributedConfig.
  warnings.warn(f"`NoneType` object {warning}.", RuntimeWarning)
No argument path is provided.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fltk-testbed/fltk/__main__.py", line 93, in <module>
    __main__()
  File "/fltk-testbed/fltk/__main__.py", line 74, in __main__
    __run_op_dict[args.action](arg_path, conf_path,
  File "/fltk-testbed/fltk/launch.py", line 122, in launch_extractor
    download_datasets(args, conf)
  File "/fltk-testbed/fltk/core/distributed/extractor.py", line 22, in download_datasets
    data_path = config.get_data_path()
AttributeError: 'NoneType' object has no attribute 'get_data_path'
```

**Expected behavior/code**
Datasets should be downloaded to `data` dir.

**Environment**
- Python version: 3.8
- Platform: Windows (WSL 2)

**Possible Solution**
Seems to be caused by a mismatch between the parameter name for the configuration.
Provided (`config`):
https://github.com/JMGaljaard/fltk-testbed/blob/f8fb18da51698e98377bb57c17505d31d7717fcf/fltk/__main__.py#L74-L81
Expected (`conf`):
https://github.com/JMGaljaard/fltk-testbed/blob/f8fb18da51698e98377bb57c17505d31d7717fcf/fltk/launch.py#L111-L122

**Comment by JMGaljaard** [comment]
Hi @AbeleMM, thank you for the extensive bug report, I will issue a fix later today!

**Comment by JMGaljaard** [comment]
I issued a fix on the development branch, an update to the course template will be issued later, but you can also git `git patch` to foward yourself @AbeleMM .
