### ISSUE TITLE
Number of epochs seemingly not honoured by client training function

### ISSUE THREAD

**Issue by AbeleMM** [JMGaljaard/fltk-testbed#40]
## Bug Report

**Current Behavior**
Regardless of the value of the `num_epochs` parameter in the `train` method from `fltk/core/client.py`, it appears that only a single epoch is run.

**Input Code**
Given dataset `cifar10` and network `Cifar10CNN`, the following is a condensed version of a client's logs for a training round when `num_epochs = 1`:
```
[client1] [1,     0] loss: 0.229
[client1] [1,    10] loss: 2.298
[client1] [1,    20] loss: 2.287
[client1] [1,    30] loss: 2.277
[client1] [1,    40] loss: 2.269
Train duration is 89.58029103279114 seconds
Test duration is 7.030742883682251 seconds
```
Setting `num_epochs = 3` then gives:
```
[client1] [3,     0] loss: 0.230
[client1] [3,    10] loss: 2.299
[client1] [3,    20] loss: 2.288
[client1] [3,    30] loss: 2.274
[client1] [3,    40] loss: 2.258
Train duration is 95.99584817886353 seconds
Test duration is 7.070667266845703 seconds
```

Both versions take a similar amount of time and they seem to be doing roughly the same one epoch's worth of work.

**Expected behavior/code**
Changes to the `num_epochs` param should determine the number of epochs executed by the training call.

**Comment by JMGaljaard** [comment]
You are correct, I had assumed that the implementation by @bacox was introduced in the patch set that I applied while adding federatd learning to the repo. 

I will add a solution to this using a patch similar to https://github.com/bacox/fltk/commit/0f8089ebaa43dc046649cfeb92fab6141db3158a. 


You can test locally (with a fabricated yaml file) locally as well using the following runtime configurations for PyCharm (see attached).

[runtime-config.zip](https://github.com/JMGaljaard/fltk-testbed/files/8797107/runtime-config.zip)

**Comment by JMGaljaard** [comment]
See release v.0.2.2 for the updated codebase that addresses this issue

**Comment by AbeleMM** [comment]
Thanks for the quick fix!
